# Generated by Django 3.2.1 on 2021-05-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pertanyaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertanyaan',
            name='bobot',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
