# Generated by Django 3.2.1 on 2021-06-09 01:43

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('isi', models.TextField(default='')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='HasilDeteksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil_hitung', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=255)),
                ('bobot', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('ttl', models.DateField()),
                ('umur', models.IntegerField()),
                ('jenis_kelamin', models.CharField(max_length=255)),
                ('pekerjaan', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=255)),
                ('bobot', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TingkatDepresi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depresi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Penanganan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('isi', models.TextField(default='')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('tingkatdepresi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tingkatdepresi')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPertanyaanJawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_1', models.IntegerField()),
                ('jawaban_2', models.IntegerField()),
                ('jawaban_3', models.IntegerField()),
                ('jawaban_4', models.IntegerField()),
                ('jawaban_5', models.IntegerField()),
                ('jawaban_6', models.IntegerField()),
                ('jawaban_7', models.IntegerField()),
                ('jawaban_8', models.IntegerField()),
                ('jawaban_9', models.IntegerField()),
                ('jawaban_10', models.IntegerField()),
                ('jawaban_11', models.IntegerField()),
                ('jawaban_12', models.IntegerField()),
                ('jawaban_13', models.IntegerField()),
                ('jawaban_14', models.IntegerField()),
                ('jawaban_15', models.IntegerField()),
                ('jawaban_16', models.IntegerField()),
                ('jawaban_17', models.IntegerField()),
                ('jawaban_18', models.IntegerField()),
                ('jawaban_19', models.IntegerField()),
                ('jawaban_20', models.IntegerField()),
                ('hasildeteksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hasildeteksi')),
            ],
        ),
        migrations.AddField(
            model_name='hasildeteksi',
            name='pengguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pengguna'),
        ),
        migrations.AddField(
            model_name='hasildeteksi',
            name='tingkatdepresi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tingkatdepresi'),
        ),
    ]
