# Generated by Django 3.2.1 on 2021-05-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='isi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='penanganan',
            name='isi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pencegahan',
            name='isi',
            field=models.TextField(default=''),
        ),
    ]
