# Generated by Django 3.2.1 on 2021-05-06 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210506_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPertanyaanJawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HasilDeteksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hasildeteksi')),
                ('Jawaban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jawaban')),
                ('Pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pertanyaan')),
            ],
        ),
    ]
