# Generated by Django 3.2.1 on 2021-05-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210507_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='createdBy_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hasildeteksi',
            name='pengguna_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historypertanyaanjawaban',
            name='HasilDeteksi_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historypertanyaanjawaban',
            name='Jawaban_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historypertanyaanjawaban',
            name='Pertanyaan_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='penanganan',
            name='createdBy_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='penanganan',
            name='tingkat_depresi_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pencegahan',
            name='createdBy_id',
            field=models.IntegerField(null=True),
        ),
    ]
