# Generated by Django 3.2.1 on 2021-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210507_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasildeteksi',
            name='pengguna_id',
            field=models.IntegerField(),
        ),
    ]
